### ISSUE TITLE
Fix scrolling in ListView

### ISSUE THREAD

**Issue by a0134234** [cs2103jan2016-f13-1j/main#45]

**Comment by ysqty** [comment]
Issue is fixed.
Refer to commit [a899fe97e5aa8a8a77ad551d20d78c74a6ff6845](https://github.com/cs2103jan2016-f13-1j/main/commit/a899fe97e5aa8a8a77ad551d20d78c74a6ff6845)

**Comment by Jxxxxx** [comment]
Task #33 #36 #38 #44
