### ISSUE TITLE
Task item's selection in the ListView are not maintained after user's undo/redo operation

### ISSUE THREAD

**Issue by ysqty** [cs2103jan2016-f13-1j/main#52]

**Comment by Jxxxxx** [comment]
#15 #16 #17 #36

**Comment by ysqty** [comment]
Issue closed.
Refer commit [fdc79f1d3e8e99bf2bac718bce3a31ae833c2bc5](https://github.com/cs2103jan2016-f13-1j/main/commit/fdc79f1d3e8e99bf2bac718bce3a31ae833c2bc5)
